# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: yarn
      - run: npm run build --if-present
      - run: cd
      - name: Copy files via SSH
        uses: appleboy/scp-action@v0.1.3
        with:
          host: 18.139.145.31
          username: ubuntu
          key: ssh-action-runner
          source: "build/*"
          target: "/var/www/test/html"
      # - run: sudo cp -r . /var/www/test/html
      # - run: sudo service nginx restart
